bibliotecalocal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), path('catalogo/', include('catalogo.urls')),
    path('', RedirectView.as_view(url='/catalogo/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
] #Es lo mismo que agregarla arriba, entre los corchetes.


#El path('', RedirectView.as_view... tenía un slash entre las comillas, lo cual me arrojaba la excepción:
# WARNINGS: ?: (urls.W002) Your URL pattern '/' has a route beginning with a '/'. Remove this slash as it is 
# unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
 

catalogo/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'), url(r'^libros/$', views.VistaListaDeLibros.as_view(), name='libros'), url(r'^libro/(?P<pk>\d+)$', views.VistaDetalleDeLibro.as_view(), name='libro-detail'), url(r'^autores/$', views.VistaListaDeAutores.as_view(), name='autores'), url(r'^autor/(?P<pk>\d+)$', views.VistaDetalleDeAutor.as_view(), name='autor-detail'),] #Recuerda que con este mapeador estamos creando nuestras urls y emparejando simultaneamente (catalogo/libros y catalogo/libro-detail/número_id. También recuerde que se llegó a este mapeador de la aplicación catalogo, desde la entrada principal a la aplicación, es decir desde el mapeador principal (..., path('catalogo/', include('catalogo.urls'),...)que se encuentra en urls.py en la carpeta de entrada (bibliotecalocal).
#Como VistaDetalleDeLibro.as_view() es una vista genérica que depende del url 'libro', me exige que name sea libro-detail, dónde -detail es reservado por django y libro como minúscula del modelo Libro.

urlpatterns += [
    path('librosUsuario/', views.VistaEjemplaresParaLosUsuarios.as_view(), name='VistaUsuarios'),
] 

urlpatterns += [
    path('bibliotecariosPermiso1/', views.VistaEjemplaresParaBibliotecarios1.as_view(), name='VistaBibliotecarios1'),
]

urlpatterns += [
    path('bibliotecariosPermiso2/', views.VistaEjemplaresParaBibliotecarios2.as_view(), name='VistaBibliotecarios2'),
]

urlpatterns += [
    path('libro/<uuid:pk>/renovar/', views.RenovacionLibroPorLibrero, name='librosRenovPorLibrero'),
]

#Como se vió anteriormente, el parámetro name de la función path con los valores autor-create, autor-update, nombreCampo-delete, tienen la sintaxis nombreCampo-tipoDeOperación, dónde tipoDeOperación tiene los nombres reservados create, update y delete que los emparejará automaticamente con los nombres reservados de plantillas, nombreCampo_form.html (autor_form.html para este ejemplo) para las operaciones de creación y actualización, y nombreCampo_confirm_delete.html, para el borrado (parametro name=autor-delete en la función path).
urlpatterns += [
    path('autor/crear/', views.CrearAutor.as_view(), name='autor-create'),
    path('autor/<int:pk>/actualizar/', views.ActualizarAutor.as_view(), name='autor-update'),
    path('autor/<int:pk>/borrar/', views.BorrarAutor.as_view(), name='autor-delete'),
]

urlpatterns += [
    path('libro/crear/', views.CrearLibro.as_view(), name='libro-create'),
    path('libro/<int:pk>/actualizar/', views.ActualizarLibro.as_view(), name='libro-update'),
    path('libro/<int:pk>/borrar/', views.BorrarLibro.as_view(), name='libro-delete'),
]

catalogo/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Genero(models.Model):
    """
    Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.).
    """
    nombre = models.CharField(max_length=200, help_text="Ingrese el tipo de género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.nombre

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Libro(models.Model):
    """
    Modelo que representa un libro (pero no un Ejemplar específico).
    """

    titulo = models.CharField(max_length=200)

    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber tener diversas títulos en la biblioteca.
    # 'Autor' es un string no un objeto.
    resumen = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")
    isbn = models.CharField('ISBN',max_length=13, help_text='hasta 13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genero = models.ManyToManyField(Genero, help_text="seleccione un genero para este libro.")
    # ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.

    lenguaje = models.ForeignKey('Lenguaje', on_delete=models.SET_NULL, null=True)

    def display_genero(self):
        """
        Creates a string for the Genero. This is required to display genre in Admin."""
        return ', '.join([ genero.nombre for genero in self.genero.all()[:3] ])     
    display_genero.short_description = 'Genero'

    def __str__(self):
        """
        String que representa al objeto Libro
        """
        return self.titulo

    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Libro
        """
        return reverse('libro-detail', args=[str(self.id)])

import uuid # Requerida para las instancias de libros únicos.

class EjemplarEspecifico(models.Model):
    """
    Modelo que representa una copia específica de un libro (Una copia que puede ser prestada por la biblioteca). Como cada clae es un modelo, que a su vez representa una tabla en al base de datos, por lo tanto puede tener muchos atributos-campos tipo objetos models.ForeingKey, pero sólo uno tipo primary_key, bajo la formo de objeto models.UUIDField. Note que el identificador-apuntador hacia este objeto se torna al color tipo clase o función.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    libro = models.ForeignKey('Libro', on_delete=models.SET_NULL, null=True)
    impresion = models.CharField(max_length=200)
    devolucion = models.DateField(null=True, blank=True)
    prestatario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True) #Note que el argumento de primero en la instanciación del objeto/clase, models.ForeingKey, User, representa una tabla o clase implicita de django, consistente en todos los usuarios de la aplicación django, guardados en la base de datos.
    campoConstante = 'xxx' #Podemos meter un atributo-campo como una constante simbólica. Todos los registros o filas tendrán este valor en su campo o columna.
    PRESTAMO_STATUS = (
        ('m', 'Mantenimiento'),
        ('p', 'Prestado'),
        ('d', 'Disponible'),
        ('r', 'Reservado'),
    )

    status = models.CharField(max_length=1, choices=PRESTAMO_STATUS, blank=True, default='m', help_text='Estatus en que se encuentra actualmente el ejemplar específico.')

    class Meta:
        ordering = ["devolucion"]
        permissions = (("permisoBibliotecario1", "Permiso tipo 1 sólo para bibliotecarios"), ("permisoBibliotecario2", "Permiso tipo 2 sólo para bibliotecarios"), ("unPermisoX", "Un permiso de hacer x cosa a x usuario."), )
#Recuerde que al crear permisos, estos no se incorporarán automáticamente al grupo o usuario particular al cual deseamos agregarlo: apareceran como nuevos permisos de la forma, específicamente para este ejemplo, catalogo | ejemplar especifico | Permiso tipo 1 sólo para bibliotecarios, en el recuadro permissions de la página Change group del sitio de administración django. Igual para los otros permisos que se definan. 
    def __str__(self):
        """
        String para representar el Objeto del Modelo
        """
        return '%s (%s)' % (self.id, self.libro.titulo)

    #@property  #No se para que sirve este decorador, de hecho está comentado y no pasó nada.
    def esta_atrasado(self): #Método-atributo para determinar si está atrasado en la devolución.
        if self.devolucion and date.today() > self.devolucion:
            return True
        return False

class Autor(models.Model):
    """
    Modelo que representa un autor
    """
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    fecha_muerte = models.DateField('Muerte', null=True, blank=True)

    def get_absolute_url(self):
        """
        Retorna la url para acceder a una instancia particular de un autor.
        """
        return reverse('autor-detail', args=[str(self.id)])

    def __str__(self):
        """
        String para representar el Objeto Modelo
        """
        return '%s, %s' % (self.nombre, self.apellido)

class Lenguaje(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    nombre = models.CharField(max_length=200,
                            help_text="Introduzca el idioma del libro.")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.nombre

catalogo/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class FormRenovLibro(forms.Form):
    #Definimos el atributo-campo de tipo DateField, campoFechaDeRenovacion:
    campoFechaDeRenovacion = forms.DateField(help_text="Introduzca una fecha entre ahora y 4 semanas (predeterminado 3 semanas).", label="Ingrese fecha de renovación")

    def clean_campoFechaDeRenovacion(self): #Ojo: la palabra clean_ en el nombre de este método es reservada de django. El método clean_... se puede decir que es una especie de método "semi-builtin" de django, cuyo nombre debe tener la sintaxis clean_nombreDelCampoQueSeEvalúa. En este caso como estamos usando el campo atributo de esta clase, campoFechaDeRenovacion, de tipo forms.DateField, el nombre del atributo-método debe ser, clean_campoFechaDeRenovacion. Este es un método que lo ejecuta django automáticamente, cada vez que se evalúa el método is_valid() en la vista basada en función, RenovacionLibroPorLibrero de este ejemplo. En base al resultado de la ejecución de dicha vista, de ser válido el resultado, dirige o envía al usuario a la plantilla html referenciada con los datos pertinentes a reverse('VistaBibliotecarios1'). En caso de no ser válida (fecha para entrega anterior a la actual, o más allá de las 4 semanas), redirige nuevamente a la plantilla actual (libroRenovadoPorLibrero.html), con la impresión de los mensajes de error configurados para el caso, en los constructores ValidationError(), los cuales colocará encima del control-formulario, formu.as_table. Perdí un día en descubrir esto (por el método de tirar flechas o ensayo y error, por no saber bién la teoría).
        data = self.cleaned_data['campoFechaDeRenovacion'] #El atributo cleaned_data limpiará la entrada del campo, cambiando el formato del texto introducido por el usuario, en un sólo tipo predefinido por el usuario django(desarrollador), haciéndolo consistente. En este ejemplo se refiere al formato en que el usuario introduzca la fecha (dd-mm-aa, aa-mm-dd, dd/mm/aa, etc.), o desplegando un mensaje de error si se intenta ingresar texto diferenta a fechas como texto normal, caracteres no validos para enviar contenido malicioso al servidor, ataques con inyecciones sql, etc.

        # Chequea si la fecha de renovación introducida no está en el pasado.
        if data < datetime.date.today():
            raise ValidationError(_('Fecha inválida! - intenta renovar a una fecha pasada!'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Fecha inválida! - intenta renovar a una fecha más alla de las 4 semanas...'))

        # Remember to always return the cleaned data.
        return data

catalogo/templates/catalogo/LibrosPrestadosAlUsuario.html
<!-- Plantilla ejemplarespecifico_list_prestado_user.html-->

{% extends "base_generica.html" %}

{% block content %}
    <h1>Libros Prestados:</h1>

    {% if ejemplarespecifico_list %}
    <ul>

      {% for instancia in ejemplarespecifico_list %}
      <li class="{% if instancia.esta_atrasado %}text-danger{% endif %}">
        <a href="{% url 'libro-detail' instancia.libro.pk %}">{{instancia.libro.titulo}}</a> ({{ instancia.devolucion }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalogo/templates/catalogo/autor_confirm_delete.html
{% extends "base_generica.html" %}

{% block content %}

<h1>Borrar Autor</h1>

<p>Esta seguro de querer borrar el autor: {{ autor }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Si, borrar.">
</form>

{% endblock %}

catalogo/templates/catalogo/autor_detail.html
<!-- Plantilla de la vista genérica VistaDetalleDeAutor(generic.DetailView), autor_detail.html-->

{% extends "base_generica.html" %}

{% block content %}
  <h1>Autor: {{ autor.apellido }},&nbsp{{ autor.nombre }} </h1>
  <p>{{ autor.fecha_nacimiento }}, &nbsp{{autor.fecha_muerte}}</p>
  <div style="margin-left:20px;margin-top:20px">
  <h3>Libros escritos por el autor registrados en la bliblioteca ({{ autor.libro_set.all.count }})</h3><!--Para la cantidad de libros u obras creadas por el autor, autor.libro_set.all.count representa un entero con el número de objetos en dicha colección. Como hemos dicho antes, el all es prescindible.-->

  {% for obra in autor.libro_set.all %}<!--Recordar que esta expresión se construye a partir del campo autor como clave foránea en la tabla (modelo o clase), Libro, referenciada aquí por convensión de sintaxis django en minúscula, expresión (autor.libro_set.all), que identifica a la colección de todos los registros (instancias, objetos) en la tabla Libros relacionados con el autor específicado por la url con id, que se usa para este documento. Aquí el all si es imprescindible.-->
    <p><a href="{{ obra.get_absolute_url }}">{{obra.titulo}}</a>(Hay &nbsp {{obra.ejemplarespecifico_set.all.count}} &nbsp copia{{ obra.ejemplarespecifico_set.all.count|pluralize }} en la biblioteca):</p><!--Note la referencia de hipertexto (href) en el ancla (a de anchor) para dirigir al documento de detalle de una obra o libro del autor, renderizando su plantilla respectiva (libro_detail.html), apuntado por la variable de plantilla, obra.titulo. Note como obtengo la cantidad total de ejemplares específicos para dicha obra o libro particular del autor en cuestión, que hay actualmente en la biblioteca. También note como funciona el colocador de s para pluralizar, |pluralize. -->
   <div style="margin-left:10px;margin-top:2px">
    <p>{{obra.resumen}}</p>
   </div>
  {% endfor %}
  </div>
{% endblock %}

catalogo/templates/catalogo/autor_form.html
{% extends "base_generica.html" %}

{% block content %}
  {# Como esta plantilla es de uso común para autor-update y autor-create (dos vistas diferentes), usamos un filtro de plantilla yesno: si el objeto existe (diferente de None) será yes, esto supone que estamos en una acualización, y se tomará la primera frase 'ACTUALIZACIÓN DE': #}
  <h3> {{ object|yesno:'ACTUALIZACIÓN DE, INGRESO DE NUEVO' }} AUTOR</h3>
  <form action="" method="post"> 
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Enviar">
  </form>
{% endblock %}

catalogo/templates/catalogo/autor_list.html
<!-- Plantilla de la vista genérica VistaListaDeAutores(generic.ListView), autor_list.html-->

{% extends "base_generica.html" %}

{% block content %}
    <h1>Lista de Autores</h1>

    {% if autor_list %} <!-- autor_list es una variable de plantilla del tipo nombreDeModelo(campo)_list (_list es un calificador reservado de django, no arbitrario). -->
    <ul>

      {% for autor in autor_list %}<!--como dijimos arriba, _list es una palabra resevada de django -->
      <li>
        <a href="{{ autor.get_absolute_url }}">{{ autor.apellido }}, &nbsp;{{autor.nombre}}</a>&nbsp({{ autor.fecha_nacimiento }}, &nbsp{{autor.fecha_muerte}})&nbsp{% if perms.catalogo.permisoBibliotecario1 %}<a href="{% url 'autor-update' autor.id %}">Actualizar</a>&nbsp<a href="{% url 'autor-delete' autor.id %}">Borrar</a>{% endif %}
<!-- recuerde, espacio en blanco en html es &nbsp. Para este caso se puede colocar dentro de las etiquetas anchor (</a></a>) o fuera de ella. Hace el mismo efecto de espacio en blanco. -->

      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay autores registrados aún en la librería.</p>
    {% endif %} 
{% endblock %}

catalogo/templates/catalogo/libroRenovadoPorLibrero.html
{% extends "base_generica.html" %}

{% block content %}
  <h1>Renovar: {{ libro_instancia.libro.titulo }}</h1>
  <p>Prestatario: {{ libro_instancia.prestatario }}</p>
  <p{% if libro_instancia.esta_atrasado %} class="text-danger"{% endif %}>Fecha de vencimiento: {{ libro_instancia.devolucion }}</p>
  <p></p>
  <form action="" method="POST">
    {% csrf_token %}
    <table>
    	{{ widget_txtBox1.as_table }}
    </table>
    <input type="submit" value="Enviar">
  </form>
{% endblock %}

catalogo/templates/catalogo/libro_confirm_delete.html
{% extends "base_generica.html" %}

{% block content %}

<h1>Borrar Libro</h1>

<p>Esta seguro de querer borrar el libro: {{ libro }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Si, borrar.">
</form>

{% endblock %}

catalogo/templates/catalogo/libro_detail.html
<!-- Recuerde: el nombre de esta plantilla vinculada a una vista genérica de tipo detalle para el modelo Libro, debe tener el nombre nombreModeloMinúscula_detail.html, dónde _detail es palabra reservada de django que indica que es plantilla asociada a dicho modelo en la vista genérica de este. Es una convención de django, puesto que django buscará automáticamente esta plantilla con el nombre específico nombreModeloMinúscula_detail.html, en el directorio o carpeta con el mismo nombre de la aplicación -en este caso, catalogo-, que está dentro de la carpeta con el nombre reservado templates de la aplicación, previa invocación de su vista genérica respectiva (VistaDetalleDeLibro) en views.py. Para modificar este comportamiento automático, estandar por defecto, se debe referenciar dentro de la definición de la vista genérica con algunas modificaciones. -->

<!-- Plantilla de la vista genérica VistaDetalleDeLibro(generic.DetailView), libro_detail.html-->

{% extends "base_generica.html" %}

{% block content %}
  <h1>Título: {{ libro.titulo }}</h1>

  <p><strong>Autor:</strong> <a href="{% url 'autor-detail' libro.autor.pk %}">{{ libro.autor }}</a></p> <!-- Fíjese como se hace la referencia a la plantilla documento de la vista genérica autor_detail.html autor -->
  <p><strong>Resumen:</strong> {{ libro.resumen }}</p>
  <p><strong>ISBN:</strong> {{ libro.isbn }}</p>
  <p><strong>Lenguaje:</strong> {{ libro.lenguaje }}</p>
  <p><strong>Genre:</strong> {% for genero in libro.genero.all %} {{ genero }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px"> 
    <h4>Copias:</h4>
      
    {% for copy in libro.ejemplarespecifico_set.all %}<!--Sintaxis: note que copy es palabra reservada de django, un elemento para iterar sobre el conjunto de registros con sintaxis, campoClaveForánea.nombreDelModeloEnMinúscula_set.all. ejemplarespecifico es el modelo (clase) en minúscula de EjemplarEspecifico (representa la tabla dónde se encuentra la clave principal(id), al igual que libro representa el campo libro de dicho modelo o tabla, que representa la tabla (modelo) de la clave externa o foránea, que sería el modelo Libro.-->
    <hr> <!-- esta hr (horizontal rule) es para poner la barra horizontal, y se implementa sólo como etiqueta de apertura.-->
    <p class="{% if copy.status == 'd' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p><!-- Note que en .get_status_display, status es el campo de la clave principal en el modelo EjemplarEspecifico (ejemplarespecifico). La sintaxis es entonces: .get_nombreCampo_display. Note la proposición compuesta class="{% if copy.status ==... dentro de la etiqueta de marcado de apertura de párrafo.-->
    {% if copy.status != 'd' %}<p><strong>Para ser retornado el:</strong> {{copy.devolucion}}</p>{% endif %}
    <p><strong>Impresión:</strong> {{copy.impresion}}</p><!-- Por su puesto, la sintaxis para manejar los campos de item del modelo usado, expresada en la palabra reservada copy durante la iteración for, es: copy.nombreCampo. Aqui vemos copy.impresion usada como variable de plantilla {{copy.impresion}}-->
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalogo/templates/catalogo/libro_form.html
{% extends "base_generica.html" %}

{% block content %}
  {# Como esta plantilla es de uso común para libro-update y libro-create (dos vistas diferentes), usamos un filtro de plantilla yesno: si el objeto existe (diferente de None) será yes, esto supone que estamos en una acualización, y se tomará la primera frase 'ACTUALIZACIÓN DE': #}
  <h3> {{ object|yesno:'ACTUALIZACIÓN DE, INGRESO DE NUEVO' }} LIBRO</h3>
  <form action="" method="post"> 
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Enviar">
  </form>
{% endblock %}

catalogo/templates/catalogo/libro_list.html
<!-- Recuerde: el nombre de esta plantilla vinculada a una vista genérica de tipo list para el modelo Libro, debe tener el nombre nombreModeloMinúscula_list.html, dónde _list es palabra reservada de django que indica que es plantilla asociada a dicho modelo en la vista genérica de este. Es una convención de django, puesto que django buscará automáticamente esta plantilla con el nombre específico nombreModeloMinúscula_list.html, en el directorio o carpeta con el mismo nombre de la aplicación -en este caso, catalogo-, que está dentro de la carpeta con el nombre reservado templates de la aplicación, previa invocación de su vista genérica respectiva (VistaListaDeLibros) en views.py. Para modificar este comportamiento automático, estandar por defecto, se debe referenciar dentro de la definición de la vista genérica con algunas modificaciones. -->


<!-- Plantilla de la vista genérica VistaListaDeLibros(generic.ListView), libro_list.html-->
{% extends "base_generica.html" %}

{% block content %}
    <h1>Lista de Libros</h1>

    {% if libro_list %} <!-- libro_list es una variable de plantilla del tipo nombre_del_modelo_list (_list es un calificador reservado de django). -->
    <ul>

      {% for libro in libro_list %}<!--como dijimos arriba, _list es una palabra resevada de django, no arbitraria del usuario. -->
      <li>
        <a href="{{ libro.get_absolute_url }}">{{ libro.titulo }}</a> ({{libro.autor}})&nbsp{% if perms.catalogo.permisoBibliotecario1 %}<a href="{% url 'libro-update' libro.id %}">Actualizar</a>&nbsp<a href="{% url 'libro-delete' libro.id %}">Borrar</a>{% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay libros en la librería.</p>
    {% endif %} 
{% endblock %}

catalogo/templates/catalogo/vista_bibliotecarios1.html
<!-- Plantilla vista_bibliotecarios1.html -->

{% extends "base_generica.html" %}

{% block content %}
    <h1>Libros Prestados:</h1>

    {% if ejemplarespecifico_list %}
    <ul>
<!--Recuerde que ejemplaresespecificos_list es un identificador builtin de django que por norma de sintaxis, tiene el formato nombreModeloEnMinúsculas_list, y que identifica-apunta-referencia a una colección de objetos, EjemplarEspecifico.objects, producto del filtrado get_queryset a base del criterio de status, prestados ('p'), de la vista basada en clase derivada de generic.ListView, VistaEjemplaresParaBibliotecarios1, en el módulo views.py, y enlazada o dirigida desde la plantilla base_generica.html, a través de la referencia de hipertexto, href="{% url 'VistaBibliotecarios1' %} presente en dicha plantilla de origen.-->
      {% for instancia in ejemplarespecifico_list %}
      <li>
        <a href="{% url 'libro-detail' instancia.libro.pk %}">{{instancia.libro.titulo}}</a> <font class="{% if instancia.esta_atrasado %}text-danger{% endif %}">({{ instancia.devolucion }})</font>, al usuario: {{ instancia.prestatario.username }} {% if perms.catalogo.permisoBibliotecario1 %}<a href="{% url 'librosRenovPorLibrero' instancia.id %}">Renovar</a>{% endif %}


      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalogo/templates/catalogo/vista_bibliotecarios2.html
<!-- Plantilla vista_bibliotecarios2.html-->

{% extends "base_generica.html" %}

{% block content %}
    <p>El usuario {{ user.get_username }} 
       {% if auth.Group is not None %}
         pertenece al grupo 
         {% for grupo in user.groups.all %}
           {{ grupo.name }}, 
         {% endfor %}
       {% else %}
         no pertenece a ningún grupo,
       {% endif %}
       y tienen tanto el permiso nivel 1, como el nivel 2.
    </p>
    <p>Este es un formulario sin ningun enlace funcional de ejemplo aquí:</p>
    <label for="txtBox1">Etiqueta para txtBox1: </label><!--Etiqueta para el control asociado con id="txtBox1"-->
    <input id="txtBox1" type="" name="nomtxtBox1" value="Texto ini txtBox1" ><!--txtBox1.  -->
    <input type="button" value="OK"><br><!--Botón para txtBox1 -->
    <input id="txtBox2" type="" name="nomtxtBox2" value="Texto ini txtBox2" ><br><!--txtBox2. Recuerde, <br> es break, y representa un salto de línea(retorno de carro).-->
    <input id="txtBox3" type="" name="nomtxtBox3" value="Texto ini txtBox3" ><!--txtBox2-->
        
{% endblock %}
<!-- Todo este código a nivel de la plantilla es mucho menos eficiente que implementarlo a nivel de las vista en una función. Se hace aquí solamente con fines didácticos, para esta práctica con programación de plantillas. -->